/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace grafo_thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class aresta : TBase
  {
    private int _vertice_ini;
    private int _vertice_fim;
    private bool _bidirecional;
    private double _peso;
    private string _desc;

    public int Vertice_ini
    {
      get
      {
        return _vertice_ini;
      }
      set
      {
        __isset.vertice_ini = true;
        this._vertice_ini = value;
      }
    }

    public int Vertice_fim
    {
      get
      {
        return _vertice_fim;
      }
      set
      {
        __isset.vertice_fim = true;
        this._vertice_fim = value;
      }
    }

    public bool Bidirecional
    {
      get
      {
        return _bidirecional;
      }
      set
      {
        __isset.bidirecional = true;
        this._bidirecional = value;
      }
    }

    public double Peso
    {
      get
      {
        return _peso;
      }
      set
      {
        __isset.peso = true;
        this._peso = value;
      }
    }

    public string Desc
    {
      get
      {
        return _desc;
      }
      set
      {
        __isset.desc = true;
        this._desc = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool vertice_ini;
      public bool vertice_fim;
      public bool bidirecional;
      public bool peso;
      public bool desc;
    }

    public aresta() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                Vertice_ini = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                Vertice_fim = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Bool) {
                Bidirecional = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.Double) {
                Peso = iprot.ReadDouble();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.String) {
                Desc = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("aresta");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.vertice_ini) {
          field.Name = "vertice_ini";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Vertice_ini);
          oprot.WriteFieldEnd();
        }
        if (__isset.vertice_fim) {
          field.Name = "vertice_fim";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Vertice_fim);
          oprot.WriteFieldEnd();
        }
        if (__isset.bidirecional) {
          field.Name = "bidirecional";
          field.Type = TType.Bool;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(Bidirecional);
          oprot.WriteFieldEnd();
        }
        if (__isset.peso) {
          field.Name = "peso";
          field.Type = TType.Double;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteDouble(Peso);
          oprot.WriteFieldEnd();
        }
        if (Desc != null && __isset.desc) {
          field.Name = "desc";
          field.Type = TType.String;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Desc);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("aresta(");
      bool __first = true;
      if (__isset.vertice_ini) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Vertice_ini: ");
        __sb.Append(Vertice_ini);
      }
      if (__isset.vertice_fim) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Vertice_fim: ");
        __sb.Append(Vertice_fim);
      }
      if (__isset.bidirecional) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Bidirecional: ");
        __sb.Append(Bidirecional);
      }
      if (__isset.peso) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Peso: ");
        __sb.Append(Peso);
      }
      if (Desc != null && __isset.desc) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Desc: ");
        __sb.Append(Desc);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
